"""initial

Revision ID: 4701ebcdc6a2
Revises: 
Create Date: 2020-07-18 17:10:52.386810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4701ebcdc6a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('ingredients', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latte')
    # ### end Alembic commands ###
