"""ingredients length increased

Revision ID: 73c2fb01238e
Revises: 4701ebcdc6a2
Create Date: 2020-07-18 21:34:58.349640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c2fb01238e'
down_revision = '4701ebcdc6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('latte', 'ingredients',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('latte', 'ingredients',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###
